/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_yinctrl_dao_YinCtrlDao */

#ifndef _Included_org_yinctrl_dao_YinCtrlDao
#define _Included_org_yinctrl_dao_YinCtrlDao
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_yinctrl_dao_YinCtrlDao
 * Method:    getReadpower
 * Signature: ()Lorg/yinctrl/pojo/Input;
 */
JNIEXPORT jobject JNICALL Java_org_yinctrl_dao_YinCtrlDao_getReadpower
  (JNIEnv *, jobject);

/*
 * Class:     org_yinctrl_dao_YinCtrlDao
 * Method:    getdevices
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_yinctrl_dao_YinCtrlDao_getdevices
  (JNIEnv *, jobject);

/*
 * Class:     org_yinctrl_dao_YinCtrlDao
 * Method:    startepoll
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_yinctrl_dao_YinCtrlDao_startepoll
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
